version: '3'
services:
  minio1:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "FAKE_ACCESS_KEY"
      MINIO_SECRET_KEY: "FAKE_SECRET_ACCESS_KEY"
    command: "server /data"
